language: csharp
matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
      mono: none
      dotnet: 1.0.1
before_script:
  - dotnet --info
  - dotnet restore
script:
  - dotnet build
